### ISSUE TITLE
Refactor distributed table metadata

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1728]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

For distributed table metadata, we have:

- `TableGlobalValue` for table info and regions placement in Datanode
- `TableRouteValue` for region route info for Frontend handling requests
- `TableRegionalValue` for Datanodes recognizing regions belonging to themselves
  - We should review `TableRegionalValue` again. Maybe it's not best designed now?

The queries and updates for these values are a bit messy now. It's better to do some refactr to achieve:

- more clear APIs to reads and writes (consider a unified mod in crate `common-meta`)
- updates to table metadata should be atomic, since the 3 are closely related (could be some "versioning", and using etcd txn maybe)

**Comment by evenyag** [comment]
Some thoughts:
1. We should also use the table id instead of the table name as a part of the key
2. Consider changing the delimiter from `-` to `/`
3. Maybe also introduce an id for catalog and schema name in the metadata
4. The key prefix should be more readable


Reference
- databend's `meta::app::schema` mod contains its key design. e.g. [keys for table](https://github.com/datafuselabs/databend/blob/main/src/meta/app/src/schema/table.rs#L788)
