### ISSUE TITLE
Table metadata desgin document and micro benchmark

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2001]
### What type of enhancement is this?

Performance, Tech debt reduction

### What does the enhancement do?

After #1985 , we successfully refactored the table metadata in distributed mode, but missed some performance microbenchmarks and the design document, especially the metadata key format.

Let us do these jobs ASAP.

The microbenchmarks of table metadata operations may give us some insights into the potential performance bottleneck and help to resolve them.

**Comment by WenyXu** [comment]
After #1985, we introduced many small transactions(like the following), and It's a nightmare to ensure the whole `on_update_metadata` is idempotent. 🥲

```rust
  async fn on_update_metadata(){
      update_table_info_kv().await();
      failpoint!('after_update_table_info');

      update_tableroute_kv().await();
      failpoint!('after_update_table_route');
      ....
  }

```


BTW, If we decided to use a large transaction instead of many small transactions(I guess we will, for two reasons: 1, the Etcd's linearized writes are expensive, 2. it reduces the number of fail points). Considers designing transactions like the following: 
```rust
  async fn on_update_metadata(){
      let ignore_if_primary_key_updated = |x| {...}
      let txn = transaction::with_primary_key(primary_key, not_exists, ignore_if_primary_key_updated);
      
      update_table_info_kv(txn).await();

      update_tableroute_kv(txn).await();
      ....
      txn.await()?;
  }
``` 

WDYT @MichaelScofield  @fengjiachun @Fengys123

**Comment by MichaelScofield** [comment]
the doc is [here](https://greptimedb.rs/common_meta/key/index.html)

**Comment by fengjiachun** [comment]
According to our current Txn API, do you mean to refactor it like this?

**Comment by fengjiachun** [comment]
Nice idea, maybe we can give it a try. cc @MichaelScofield
