### ISSUE TITLE
Wrap sqlness runner with Clap

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#2380]
### What problem does the new feature solve?

our sqlness runner `cargo sqlness` only has a very rough cli interface, which is hard to use and understand

### What does the feature do?

Wrap a clip parser to the binary. And expose more sqlness configs https://docs.rs/sqlness/latest/sqlness/struct.Config.html#structfield.test_filter

**Comment by WenyXu** [comment]
https://docs.greptime.com/developer-guide/tests/sqlness-test Does this not work?

**Comment by waynexia** [comment]
> https://docs.greptime.com/developer-guide/tests/sqlness-test#run-a-specific-test Does this not work?

It works, but we don't provide a `help` command to tell how to use it. And this is the only sqlness option we supported at present

**Comment by Lilit0x** [comment]
Hi @waynexia , I'd like to work on this improvement.
Below is a rough outline of what I will do to improve the interface with Clap.
- First, adding a help message using the description and adding usage examples
- Some worthy `sqlness` configurations that I think will be really helpful
  - `fail-fast`
  - `env_config_file` : Specifying a custom config file
  - `result_extension`: Because `.res` is also a valid result extension

Thanks you.

**Comment by waynexia** [comment]
Thanks for your enthusiasm!

>Some worthy sqlness configurations that I think will be really helpful 

👍 For `result_extension`, it's not likely to change as all the result files are tracked with git and have a fixed extension name.

**Comment by Lilit0x** [comment]
Hi there, just to confirm again, the binary in the `sqlness` crate is `sqlness-cli`, right?
https://github.com/CeresDB/sqlness/tree/main/sqlness-cli

**Comment by waynexia** [comment]
Nope, `sqlness` itself is a crate (with its own cli, but we don't use this). We build our runnable on top of the *lib sqlness*. You can find it in `tests/runner/Cargo.toml`.

**Comment by Lilit0x** [comment]
Ohh, okay.
Found it. Thanks

**Comment by evenyag** [comment]
Closed by #2400
