### ISSUE TITLE
Use row protocol to support opentsdb

### ISSUE THREAD

**Issue by fengjiachun** [GreptimeTeam/greptimedb#2444]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

In version 0.4, we support gRPC protocol based on row insert protocol. 
We are currently using the row insert protocol to support both [InfluxDB line protocol](https://github.com/GreptimeTeam/greptimedb/blob/fe5679e77e2556b2e3555d73a6c0f420c5323cb3/src/servers/src/influxdb.rs#L33) and [Prometheus remote write](https://github.com/GreptimeTeam/greptimedb/blob/4a82926d72f75315180de16cdb54fdb942861575/src/servers/src/prom_store.rs#L303).

We also provide [tools](https://github.com/GreptimeTeam/greptimedb/blob/fe5679e77e2556b2e3555d73a6c0f420c5323cb3/src/servers/src/row_writer.rs#L74) to complete the conversion to row protocol.

Now, we are using column insert protocol to support OpenTSDB, This causes the overhead of having to convert to rows when actually writing (which can be avoided).

**Comment by Lilit0x** [comment]
Hi @fengjiachun, I am interested in working on this refactor. Below is my understanding of the problem and how I might go about solving it.

As you have mentioned, it will be easier if OpenTSDB also supported the row insert protocol instead of column insert as in [here](https://github.com/GreptimeTeam/greptimedb/blob/567fbad64760f3dfccedd3bfbcaa6f4bbcae0da1/src/frontend/src/instance/opentsdb.rs#L37). 
Basically, I will want to convert the `DataPoint` type for an OpenTSDB request to a `RowInsertRequests` type to make it compatible with calling `Instance.handle_row_inserts` instead of `handle_inserts` as is defined [here](https://github.com/GreptimeTeam/greptimedb/blob/567fbad64760f3dfccedd3bfbcaa6f4bbcae0da1/src/frontend/src/instance/grpc.rs#L185).
To do that, I will use the `MultiTableData` struct to construct rows from the tags, timestamps, values (all gotten from the `DataPoint` struct) and then finally to the desired `RowInsertRequests` type.

Thank you.

**Comment by fengjiachun** [comment]
@Lilit0x You are right 👍🏻

**Comment by fengjiachun** [comment]
Hi @Lilit0x , are you still working on this issue?

**Comment by waynexia** [comment]
This might be an OOM. You can try to limit the compile job numbers by `--build-jobs`. E.g., `cargo nextest run --build-jobs 4`
