### ISSUE TITLE
Improve the object storage local cache

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2516]
### What type of enhancement is this?

Performance

### What does the enhancement do?

<img width="528" alt="object_store_cache" src="https://github.com/GreptimeTeam/greptimedb/assets/14142/fd115069-94b0-406f-82d0-0e90bde18e7c">

The [current local cache](https://github.com/GreptimeTeam/greptimedb/blob/develop/src/object-store/src/layers/lru_cache.rs) for object storage has several issues:

* The size limit of cache items is based on quantity rather than actual data size, which makes it inconvenient to limit the overall size of local cache.
* The current caching strategy is actually read-through, without any processing for writing. Therefore, there have been bugs in the past caused by updates to the manifest `__last_checkpoint`, resulting in local dirty cache. A better strategy should combine write-back, synchronously updating the cache in the local storage while writing recent data to remote object storage, improving the cache hit rate of recent hot data.

So we want to do some improvements for it:

* Use [moka](https://github.com/moka-rs/moka) as the LRU cache, it's faster and already used in our codebase.
* Based on the actual file size for LRU replacement, rather than the quantity.
* Add a "write back" strategy and introduce a write buffer to manage recently written data separately. When a query is hit, it enters the LRU management of the read cache. The default write buffer can use a simple strategy based on size-based FIFO for replacement.

**Comment by aierui** [comment]
This feature, influxdb_iox, was initially designed to download hot data from the S3 object store into memory, making it accessible to the query engine for processing. However, the decision to remove hot data caching in memory was made for two primary reasons, as far as I can recall: firstly, caching hot data in memory was found to consume a significant amount of system memory resources, potentially leading to out-of-memory (OOM) issues within the containerized environment. Secondly, fetching the required object store file for the initial query added overhead compared to reading directly from the object store, potentially causing increased query latency.

During that period, the query engine (Data Fusion) had limited support for features like pruning, projection pushdown, predicate pushdown, etc. However, I believe that these capabilities have since been significantly improved and are more comprehensive.

Nevertheless, your suggested approach of utilizing local disk storage for storing a portion of the data within the current instance can greatly enhance the efficiency of hot data queries.

**Comment by killme2008** [comment]
> This feature, influxdb_iox, was initially designed to download hot data from the S3 object store into memory, making it accessible to the query engine for processing. However, the decision to remove hot data caching in memory was made for two primary reasons, as far as I can recall: firstly, caching hot data in memory was found to consume a significant amount of system memory resources, potentially leading to out-of-memory (OOM) issues within the containerized environment. Secondly, fetching the required object store file for the initial query added overhead compared to reading directly from the object store, potentially causing increased query latency.
> 
> During that period, the query engine (Data-Fusion) had limited support for features like pruning, projection pushdown, predicate pushdown, etc. However, I believe that these capabilities have since been significantly improved and are more comprehensive.
> 
> Nevertheless, your suggested approach of utilizing local disk storage for storing a portion of the data within the current instance can greatly enhance the efficiency of hot data queries.

Thanks for your info.

In version 0.4, we have made certain improvements through #2522. However, the initial query overhead is not being processed efficiently at present. After discussing with @evenyag, we have come to the conclusion that implementing the write buffer design in the storage engine could be a viable solution. Storage engines have a better understanding of the context and can choose a suitable caching strategy. Additionally, we can also implement memory caching. 

The final caching design should be layered, including memory, local disk, cross-node sharing cache, etc.

**Comment by evenyag** [comment]
> After discussing with @evenyag, we have come to the conclusion that implementing the write buffer design in the storage engine could be a viable solution. Storage engines have a better understanding of the context and can choose a suitable caching strategy.

I'm going to write a design doc for the disk-based cache. I think I can post it in the next week. This should be a part of the tiered caching hierarchy.

**Comment by evenyag** [comment]
> I'm going to write a design doc for the disk-based cache. I think I can post it in the next week. This should be a part of the tiered caching hierarchy.

Sorry for the delay. I created a tracking issue for this and mentioned how to implement it briefly in the issue. https://github.com/GreptimeTeam/greptimedb/issues/2965

**Comment by killme2008** [comment]
Tracked in #2965
