### ISSUE TITLE
upgrade clap to 4.x

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#2742]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

The clap used in our crate `cmd` is still version 3.x, which I believe is long outdated, should be upgrade to new 4.x.

**Comment by bigboss2063** [comment]
Hi, can I take this?

**Comment by MichaelScofield** [comment]
@bigboss2063 sure, welcome!

**Comment by bigboss2063** [comment]
@MichaelScofield Hi, Scofield. When I finished my modifications and prepared to run the test, I found that the following error would be reported at the end of the compilation:
```bash
linking with `cc` failed: exit status: 1 note: LC_ALL="C" ... signal 9 [Killed]
```
This was caused by OOM, so I had to reduce the number of simultaneous build jobs to 1, causing my compilation to be very, very slow.
```toml
[build]
jobs = 1
```
This task may need to wait until I upgrade my computer in a few days, or you may have other ways to help me. I'm running greptimedb on Arch Linux in wsl2.

**Comment by bigboss2063** [comment]
Hi, Scofield @MichaelScofield, When I completed the modification and wanted to test the code, I found that an error was reported and interrupted during the compilation process. It seemed that it was caused by OOM:
```bash
error: linking with `cc` failed: exit status: 1 note: LC_ALL="C"
... 
fatal error: ld terminated with signal 9 [Killed] compilation terminated.
```
So I tried to modify the configuration:
```toml
[build]
jobs = 1
```
But even setting jobs to 2 will cause OOM. My current compilation speed is very, very slow. I can't test well.

Do you have any suggestions about this?

I will upgrade my computer, but this will cause this task that need to be completed later

**Comment by MichaelScofield** [comment]
@bigboss2063 Maybe you can increase the cpu and memory limit for WSL2? Just find two pages that might be helpful to you:
- https://learn.microsoft.com/en-us/answers/questions/1296124/how-to-increase-memory-and-cpu-limits-for-wsl2-win
- https://fizzylogic.nl/2023/01/05/how-to-configure-memory-limits-in-wsl2

**Comment by discord9** [comment]
@bigboss2063 Using swap space might alliviate this problem, this is my .wslconfig(see https://learn.microsoft.com/en-us/windows/wsl/wsl-config for more options) which added 16 GB swap space
```
[wsl2]
swapFile=<absolute path to>\\swap.vhdx
swap=16GB
```
and while compile from clean state(`cargo clean;cargo build`) it appeal to stretch thin but wouldn't oom:
```
              total        used        free      shared  buff/cache   available
Mem:       16266344     7464220     1396648       14492     7405476     8454992
Swap:      16777216     8018000     8759216
```

**Comment by bigboss2063** [comment]
Thanks for your help @MichaelScofield @discord9, I tried limiting the memory cap of wsl2 and giving it a large swap space, which worked.

However, such compilation speed is very slow, even reaching the hour level. It seems that I can only wait for my extended memory to arrive before I can start work.
