### ISSUE TITLE
Follow-up tasks of system metric

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#2975]
### What type of enhancement is this?

Other

### What does the enhancement do?

This issue tracks the follow-up tasks of https://github.com/GreptimeTeam/greptimedb/pull/2928

- [x] Avoid network when standalone and frontend are feeding themselves
- [x] Select a proper default schema for those system metric tables
- [ ] https://github.com/GreptimeTeam/greptimedb/issues/2972

cc @Taylor-lagrange

**Comment by Taylor-lagrange** [comment]
The reason why in this PR https://github.com/GreptimeTeam/greptimedb/pull/3047  is not moving `ExportMetricTask` to  plugin is that there is another similar task called `GreptimeDBTelemetryTask`. Because `GreptimeDBTelemetryTask` involves leader election in meta, there is no way to elegantly transplant it to the plugin, so the transplant was abandoned.

I think this issue can be closed, and we tracing this remain problem in https://github.com/GreptimeTeam/greptimedb/issues/2972 with `GreptimeDBTelemetryTask` and `ExportMetricTask`

**Comment by killme2008** [comment]
> The reason why in this PR #3047 is not moving `ExportMetricTask` to plugin is that there is another similar task called `GreptimeDBTelemetryTask`. Because `GreptimeDBTelemetryTask` involves leader election in meta, there is no way to elegantly transplant it to the plugin, so the transplant was abandoned.
> 
> I think this issue can be closed, and we tracing this remain problem in #2972 with `GreptimeDBTelemetryTask` and `ExportMetricTask`

ok
