### ISSUE TITLE
Check the table route type before calling `physical_table_route`

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#3016]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

https://github.com/GreptimeTeam/greptimedb/blob/feec4e289d95977f9e194fd680f7f10f52291dce/src/common/meta/src/key/table_route.rs#L65-L103

We should add `panic` notes before methods that the inside invoke the `physical_table_route`. And add a check before we invoke these methods(e.g., `matches!(table, TableRouteValue::pshyical(_))`).

**Comment by AntiTopQuark** [comment]
Hello, I would like to try this task, but I am not very familiar with  Rust and Greptime, so it might take me a bit more time. Would that be acceptable to you?

**Comment by waynexia** [comment]
Great, feel free to reach out if you have anything want to discuss

**Comment by AntiTopQuark** [comment]
I made an attempt, could you please check it for me? 
I have a question: since the `physical_table_route()` function already includes the `unreachable!` macro, why is there a need to add a check in the functions that call it at a higher level? Is it to detect errors earlier?

https://github.com/GreptimeTeam/greptimedb/pull/3023

**Comment by WenyXu** [comment]
> why is there a need to add a check in the functions that call it at a higher level? 

It should throw an error instead of panic.
