### ISSUE TITLE
move create database to procedure 

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#3591]
### What type of enhancement is this?

Refactor, Tech debt reduction

### What does the enhancement do?

We introduced multiple-level locks in the procedure, and all DDL operations should acquire all related locks during the execution. After implementing #3516, we should refactor the database creation into a procedure.

**Comment by tisonkun** [comment]
Would you add some refer impl like how other procedure are implemented?

**Comment by WenyXu** [comment]
> Would you add some refer impl like how other procedure are implemented?

Yes, a typical procedure looks like this:
https://github.com/GreptimeTeam/greptimedb/blob/623c930736e66320127480014a46ade7cf049a90/src/common/meta/src/ddl/create_table.rs#L316-L350

And more procedures can be found [here](https://github.com/GreptimeTeam/greptimedb/tree/main/src/common/meta/src/ddl)

**Comment by CookiePieWw** [comment]
Hi @WenyXu , I'd like to give it a try.

**Comment by WenyXu** [comment]
> Hi @WenyXu , I'd like to give it a try.

Have fun

**Comment by CookiePieWw** [comment]
I've made some efforts in the past few days. Since It's my first time diving into greptimedb, I think it would be better to make it clear before taking actions. Here are my findings and confusions:

- Currently, the `create database` statement is simply executed inside `create_database` method in `StatementExecutor`. The target is to refactor it as other ddl ops, which executes as follows (here I take `drop database` as an example):
  - Do some checks and then forward the params to `drop_database_procedure` method
  - Packaging the params as a task. The packaging methods are implemented in `src/common/meta/src/rpc/ddl.rs`
  - Submit the task to execute. The submission methods are implemented in `src/common/meta/src/ddl_manager.rs` and `src/common/meta/src/ddl.rs`
  - The execution methods take place under `src/common/meta/src/ddl`, thus a file named `create_database.rs` should be added to implement the `CreateDatabaseProcedure`

- I've noticed that there are lots of methods and traits related to rpc like `PbDropDatabaseTask`, which lead me to greptimedb-proto finally. Is it proper to simply place a todo somewhere and leave it alone?
- I've read about the implemention of `CreateTableProcedure`. It seems the procedure executes in 3 stages with several concepts I'm not familiar yet (regions, memory allocation, etc.). Should I have a more complicated design for the procedure, or simply copy the original one into the `execute` method and acquire some locks in `lock_key`? Besides, it seems the `from_json` and `dump` methods are related to rpc as well.

Would you mind giving me some advice @WenyXu ? Thanks a lot.

**Comment by WenyXu** [comment]
> I've made some efforts in the past few days. Since It's my first time diving into greptimedb, I think it would be better to make it clear before taking actions. Here are my findings and confusions:
> 
> * Currently, the `create database` statement is simply executed inside `create_database` method in `StatementExecutor`. The target is to refactor it as other ddl ops, which executes as follows (here I take `drop database` as an example):
>   
>   * Do some checks and then forward the params to `drop_database_procedure` method
>   * Packaging the params as a task. The packaging methods are implemented in `src/common/meta/src/rpc/ddl.rs`
>   * Submit the task to execute. The submission methods are implemented in `src/common/meta/src/ddl_manager.rs` and `src/common/meta/src/ddl.rs`
>   * The execution methods take place under `src/common/meta/src/ddl`, thus a file named `create_database.rs` should be added to implement the `CreateDatabaseProcedure`
> * I've noticed that there are lots of methods and traits related to rpc like `PbDropDatabaseTask`, which lead me to greptimedb-proto finally. Is it proper to simply place a todo somewhere and leave it alone?
> * I've read about the implemention of `CreateTableProcedure`. It seems the procedure executes in 3 stages with several concepts I'm not familiar yet (regions, memory allocation, etc.). Should I have a more complicated design for the procedure, or simply copy the original one into the `execute` method and acquire some locks in `lock_key`? Besides, it seems the `from_json` and `dump` methods are related to rpc as well.
> 
> Would you mind giving me some advice @WenyXu ? Thanks a lot.

>  Is it proper to simply place a todo somewhere and leave it alone?
 
Nope, we should define the protobuf in the greeting-proto firstly.

> I've read about the implemention of CreateTableProcedure. It seems the procedure executes in 3 stages with several concepts I'm not familiar yet (regions, memory allocation, etc.). ….

Don’t worry, creating database only requires to create the metadata. Check current logical of the database creation.
