### ISSUE TITLE
Remove MySQL server in datanode

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#556]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

In standalone mode, there is no need to start MySQL server in both frontend and datanode. We can check running mode in `datanode::server::Services` and start MySQL server only in distribuited mode.

### Implementation challenges

NA

**Comment by sunng87** [comment]
@v0y4g3r just to clarify, is this designed to disable mysql server in `datanode`, or to remove mysql protocol support in standalone mode?

**Comment by v0y4g3r** [comment]
> @v0y4g3r just to clarify, is this designed to disable mysql server in `datanode`, or to remove mysql protocol support in standalone mode?

Both frontend and datanode will start MySQL server in standalone mode. 
This issue is about to disable MySQL only in datanode.

**Comment by sunng87** [comment]
Sounds good, thanks!

**Comment by MichaelScofield** [comment]
In standalone mode, why dn needs a mysql server? dn could only expose local grpc service for fe.

To be clarify:

- In standalone mode, dn starts grpc only
- In distributed mode, dn starts grpc and mysql
- In either mode, fe is communicating with dn via grpc

Mysql server in dn is only used for debugging purpose in distributed mode. Since the underlying env is unstable when dn and fe are deployed distributed, it’s good to directly manually check dn’s data. In standalone mode, because dn and fe are “packed” in one process, I think we don’t need to do that.

**Comment by sunng87** [comment]
Let me update this issue's title
