### ISSUE TITLE
Supports default value when inserting data.

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#759]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

For example:

```
CREATE TABLE integers(i BIGINT, time index(i));

INSERT INTO integers values (default);
```

It should insert the default value `null` into the table `integers`.

And if the column has a `default` constraint, it should use the default value generated by the constraint too.

**Comment by lizhemingi** [comment]
Let me take it if you don't mind.

**Comment by killme2008** [comment]
@lizhemingi  Ok, I assign it to you.

**Comment by evenyag** [comment]
I remember that we have already implemented a similar feature, but we might need to add more cases to the [integration tests](https://github.com/GreptimeTeam/greptimedb/tree/develop/tests/cases/standalone) to check whether it works.

**Comment by lizhemingi** [comment]
Had a try on 
```
CREATE TABLE integers(i BIGINT, time index(i));
INSERT INTO integers values (default);
```
Seems not working right now.

![image](https://user-images.githubusercontent.com/9639449/208366645-adae7c01-b593-4bea-a9ee-404737a60dd0.png)

**Comment by lizhemingi** [comment]
@killme2008 

What's the expected behavior when use this `default` feature on `STRING` type ? 

Since some thing like
```
CREATE TABLE integers(i BIGINT, j STRING NULL, time index(i));
INSERT INTO integers values (1, default);
```
will insert a record `i values 1 and j values "default"` right now. And the default value of j actually is `NULL`.

Should we use `quoted "default"` vs `unquoted default` to distinguish? But it still break the compatibility for `unquoted default` with current behavior. Or should we keep this default feature away from STRING type field ?

**Comment by killme2008** [comment]
@lizhemingi 

I think this is a but at https://github.com/GreptimeTeam/greptimedb/blob/develop/src/sql/src/statements/insert.rs#L69

We treat the `Identifier` as `SingleQuotedString` right now when inserting data.
