### ISSUE TITLE
Local cache for catalog

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#816]
### What type of enhancement is this?

Performance

### What does the enhancement do?

`CatalogManager`'s `schema`/`table` API in in the critical path of every table request. Current implementation is a workaround since arrow-datfusion catalog is sync method while the implementation is async, which may introduce extra overhead.

I opened an [issue for async version of `Catalog` APIs](https://github.com/apache/arrow-datafusion/issues/3777) and arrow-datafusion's async catalog api is still under development. We may end up with building a local cache for catalogs/schemas/tables.

### Implementation challenges

NA

**Comment by v0y4g3r** [comment]
As [PR for async `SchemaProvider::table`](https://github.com/apache/arrow-datafusion/pull/4607) is merged, we can now update to head version of datafusion. 

There's still one caveat, `CatalogProvider` API is still sync. We may choose another workaround like ballista, which refreshes catalog on demand.
- refresh method: [`ListingSchemaProvider::refresh`](https://github.com/apache/arrow-datafusion/blob/4d621c5c0da387f50c9ab6f3a9ee568062ee9976/datafusion/core/src/catalog/listing_schema.rs#L78)
- call site: [FlightSqlServiceImpl::create_ctx](https://github.com/spaceandtimelabs/arrow-ballista/blob/5aeec11d139f4efc08ef04b065dbddf0c9494b1a/ballista/scheduler/src/flight_sql.rs#L405)

**Comment by MichaelScofield** [comment]
A quick glimpse of datafusion and our codes, there are mainly two usage of catalog/schema manager: 1. list all tables in catalog; 2. find a specific table.

For listing tables I think we can just ignore the caching demand, because:
- In datafusion, it's been used in `information_schema` and "refreshing catalog". Neither of which we need.
- In our codes, `Tables` in `InformationSchema` is relying on it. However, I find there are no actual use of the `Tables`. Can it be deleted? @v0y4g3r 
- Also in our codes, "show databases/tables" requires it. But there are not frequent sqls. Or, the 2 sqls don't exist in any latency critical job execution path.

For finding tables, I think we can now use [moka](https://crates.io/crates/moka) to cache tables in `RemoteCatalogManager` in Datanode and `FrontendCatalogManager` in Frontend. WDYT? @v0y4g3r

**Comment by v0y4g3r** [comment]
> A quick glimpse of datafusion and our codes, there are mainly two usage of catalog/schema manager: 1. list all tables in catalog; 2. find a specific table.
> 
> For listing tables I think we can just ignore the caching demand, because:
> 
> * In datafusion, it's been used in `information_schema` and "refreshing catalog". Neither of which we need.
> * In our codes, `Tables` in `InformationSchema` is relying on it. However, I find there are no actual use of the `Tables`. Can it be deleted? @v0y4g3r
> * Also in our codes, "show databases/tables" requires it. But there are not frequent sqls. Or, the 2 sqls don't exist in any latency critical job execution path.
> 
> For finding tables, I think we can now use [moka](https://crates.io/crates/moka) to cache tables in `RemoteCatalogManager` in Datanode and `FrontendCatalogManager` in Frontend. WDYT? @v0y4g3r

Since datafusion has already refactored their requirements for table resolution, the whole "schema provider"/"catalog provider" can be removed I think.

**Comment by MichaelScofield** [comment]
Let's wait for datafusion's catalog refactor in https://github.com/apache/arrow-datafusion/issues/5291

**Comment by Fengys123** [comment]
There may be a problem:
Assuming there is a table a, and frontend also caches the info of table a. But when others alters table a, there is no mechanism to trigger the frontend's cache update. @MichaelScofield @v0y4g3r

**Comment by MichaelScofield** [comment]
You can implement heartbeat in frontend first, and make this cache invalidation in heartbeat response.

**Comment by MichaelScofield** [comment]
of course

**Comment by MichaelScofield** [comment]
completed in https://github.com/GreptimeTeam/greptimedb/pull/1592
